---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy Stage
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      # Publish ordersAPI
      if ! cf service ordersAPI > /dev/null; then
        cf cups ordersAPI
      fi

      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"

      # Update ordersAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups ordersAPI -p '{"host":"'$HOST'"}'
